services:
  - type: web
    name: librolink
    env: node
    plan: free
    buildCommand: npm run install-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        value: "not-required"
        sync: false 